/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View,Button } from 'react-native';
import wonderpush from 'react-native-wonderpush';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--'
  };
  componentDidMount() {
    wonderpush.setClientId('fd49eef17401e6b2916e9101fa48c9c2f15ec330','fd9b63c4c77c9a66d00aa64e5aed8d25e8ccb510e96baff8b08a8a980777e1c6')
  }
  render() {
    return (
      <View style={styles.container}>

        <Button
          onPress={() => {
            wonderpush.subscribeToNotifications();
          }}
          title="Subscribe to WonderPush Notifications."
          color="#841584"
          accessibilityLabel="Learn more about this purple button"/>
        <Button
          onPress={() => {
            wonderpush.unsubscribeFromNotifications();
          }}
          title="Unsubscribe to WonderPush Notifications."
          color="#841584"
          accessibilityLabel="Learn more about this purple button"/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
