/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View,Button } from 'react-native';
import WonderPush from 'react-native-wonderpush';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--'
  };
 
  constructor(){
    super();
    WonderPush.subscribeToNotifications();
  }
  componentDidMount() {
    
  }
  render() {
    return (
      <View style={styles.container}>
        <Button
          onPress={async () => {
            try {
              const response = await WonderPush.subscribeToNotifications();
              console.log(response);  
            } catch (error) {
              console.log(error);
            }
          }}
          title="Subscribe to WonderPush Notifications."
          color="#841584"
          accessibilityLabel="Learn more about this purple button"/>
        <Button
          onPress={ async () => {
            try {
              const response = await WonderPush.unsubscribeFromNotifications();
              console.log(response);  
            } catch (error) {
              console.log(error);
            }
          }}
          title="Unsubscribe to WonderPush Notifications."
          color="#841584"
          accessibilityLabel="Learn more about this purple button"/>
      <Button
          onPress={ async() => {
            try {
              const response = await WonderPush.isSubscribedToNotifications();
              console.log(response);  
            } catch (error) {
              console.log(error);
            }
          }}
          title="Check for subscription"
          color="#841584"
          accessibilityLabel="Learn more about this purple button"/>
        <Button
          onPress={ async() => {
            try {
              const response = await WonderPush.setLogging(true);
              console.log(response);  
            } catch (error) {
              console.log(error);
            }
          }}
          title="Enable Logging"
          color="#841584"
          accessibilityLabel="Learn more about this purple button"/>
        <Button
          onPress={ async() => {
            try {
              const response = await WonderPush.setLogging(false);
              console.log(response);  
            } catch (error) {
              console.log(error);
            }
          }}
          title="Disable Logging"
          color="#841584"
          accessibilityLabel="Learn more about this purple button"/>

        <Button
          onPress={ async() => {
            try {
              const response = await WonderPush.trackEvent('purchase',{'product':123});
              console.log(response);  
            } catch (error) {
              console.log(error);
            }
          }}
          title="Track Event"
          color="#841584"
          accessibilityLabel="Learn more about this purple button"/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
