# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNWonderpush' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'WonderPush', '~> 3.0'
  # Pods for RNWonderpush

end
